name = "demo-exp"
account_id = "490ebc8878106b938b84c112d545802b"
compatibility_date = "2025-07-03"
main = "./worker/index.ts"
routes = [
  { pattern = "demo.exp.originator-profile.org", custom_domain = true }
]
[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [
  "/images/favicon.ico",
  "/images/favicon2.ico",
  "/images/demo-ad-originator.png"
]
