name: wordpress_build
description: Build for WordPress plugin
runs:
  using: composite
  steps:
    - name: Build for WordPress plugin
      run: docker build --output=dist .
      working-directory: packages/wordpress
      shell: bash
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: wordpress
        path: packages/wordpress/dist/*.zip
