#!/usr/bin/env node

/**
 * Generates the "Environment" section of each package README.
 *
 * Sources (per package, with the repo root as fallback for package.json):
 *   - `engines.node` and `packageManager` -> Development
 *   - GitHub Actions `test.yml` `jobs.main.runs-on` -> Verified
 *   - `Dockerfile` (first `FROM`) base image -> Verified
 *   - `dist-<target>/manifest.json` (build output) browser / manifest support -> Verified
 *
 * Only the block between the markers is rewritten:
 *   <!-- environments-start --> ... <!-- environments-stop -->
 *
 * Usage:
 *   node scripts/update-readme-environments.ts          # update READMEs
 *   node scripts/update-readme-environments.ts --check  # exit 1 if any is stale (for CI)
 *
 * Runs in the root package.json `version` lifecycle (after build, so manifests exist).
 */
import { load } from "js-yaml";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path, { basename } from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const WORKSPACE_DIRS = ["apps", "packages"];
const START_MARKER = "<!-- environments-start -->";
const STOP_MARKER = "<!-- environments-stop -->";

type EnvMap = Record<string, string>;

type PackageJson = {
  engines?: { node?: string };
  packageManager?: string;
};

function readPackageJson(dir: string): PackageJson {
  return JSON.parse(readFileSync(path.join(dir, "package.json"), "utf8"));
}

function readdirSafe(dir: string): string[] {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

function readSafe(file: string): string | null {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return null;
  }
}

function resolveToolchain(pkg: PackageJson, root: PackageJson): string[] {
  const items: string[] = [];
  const node = pkg.engines?.node ?? root.engines?.node;
  if (node) items.push(`- Node.js: \`${node}\``);
  const pm = pkg.packageManager ?? root.packageManager;
  if (pm) {
    const [name, version] = pm.split("@");
    if (name && version) items.push(`- ${name}: \`${version.split("+")[0]}\``);
  }
  return items;
}

function deriveFromGithubActions(): EnvMap {
  const workflow = readSafe(path.join(ROOT, ".github/workflows/test.yml"));
  if (!workflow) return {};
  const os = (load(workflow) as any)?.jobs?.main?.["runs-on"];
  if (!os) return {};
  const [osName, osVersion] = os.split("-");
  return {
    OS: `${({ ubuntu: "Ubuntu", windows: "Windows", macos: "macOS" } as Record<string, string>)[osName] ?? osName} ${osVersion}`,
  };
}

function deriveFromDockerfile(dir: string): EnvMap {
  const content = readSafe(path.join(dir, "Dockerfile"));
  const match = content?.match(/^FROM\s+(\S+)/im);
  if (!match) return {};
  return {
    "Base image": `\`${match[1].split("@")[0]}\``,
  };
}

function deriveFromManifests(dir: string): EnvMap {
  let manifestVersion: string | undefined;
  let chrome: string | undefined;
  let sidePanel = false;
  let firefox: string | undefined;
  let sidebarAction = false;
  let firefoxAndroid: string | undefined;

  for (const name of readdirSafe(dir)) {
    if (name !== "dist" && !name.startsWith("dist-")) continue;
    const content = readSafe(path.join(dir, name, "manifest.json"));
    if (!content) continue;
    const m = JSON.parse(content);
    manifestVersion ??= m.manifest_version && `Manifest V${m.manifest_version}`;
    chrome ??= m.minimum_chrome_version;
    sidePanel ||= Boolean(m.side_panel);
    firefox ??= m.browser_specific_settings?.gecko?.strict_min_version;
    sidebarAction ||= Boolean(m.sidebar_action);
    firefoxAndroid ??=
      m.browser_specific_settings?.gecko_android?.strict_min_version;
  }

  const trim = (v: string) => v.replace(/\.0$/, "");
  const out: EnvMap = {};
  if (chrome) {
    const features = [manifestVersion, sidePanel && "Side Panel API"].filter(
      Boolean,
    );
    out["Google Chrome (Chromium)"] = `${chrome}+ (${features.join(", ")})`;
  }
  if (firefox) {
    const features = [
      manifestVersion,
      sidebarAction && "Sidebar Action API",
    ].filter(Boolean);
    out["Mozilla Firefox (desktop)"] =
      `${trim(firefox)}+ (${features.join(", ")})`;
  }
  if (firefoxAndroid) out["Firefox for Android"] = `${trim(firefoxAndroid)}+`;
  return out;
}

function renderBlock(pkg: PackageJson, root: PackageJson, dir: string): string {
  const scriptRel = path
    .relative(dir, path.join(ROOT, "scripts/update-readme-environments.ts"))
    .replaceAll(path.sep, "/");

  const verified: EnvMap = {
    ...deriveFromGithubActions(),
    ...deriveFromDockerfile(dir),
    ...deriveFromManifests(dir),
  };
  const toItems = (map: EnvMap = {}) =>
    Object.entries(map).map(([label, text]) => `- ${label}: ${text}`);

  const lines: string[] = [];
  const section = (title: string, items: string[]) => {
    if (items.length > 0) lines.push(`### ${title}`, "", ...items, "");
  };

  lines.push(
    `<!-- NOTE: Auto-generated by ${scriptRel} from package.json, .github/workflows/test.yml, Dockerfile, and manifest.json. Edit the source, not this section. -->`,
    "",
    "## Environment",
    "",
  );

  section("Verified", toItems(verified));
  section("Development", resolveToolchain(pkg, root));

  return lines.join("\n").trimEnd();
}

function applyBlock(readme: string, block: string): string | null {
  const start = readme.indexOf(START_MARKER);
  const stop = readme.indexOf(STOP_MARKER);
  if (start === -1 || stop === -1 || stop < start) return null;
  return `\
${readme.slice(0, start + START_MARKER.length)}

${block}

${readme.slice(stop)}`;
}

const check = process.argv.includes("--check");
const root = readPackageJson(ROOT);

const targets: { readmePath: string; readme: string }[] = [];
for (const workspace of WORKSPACE_DIRS) {
  for (const entry of readdirSafe(path.join(ROOT, workspace))) {
    const readmePath = path.join(ROOT, workspace, entry, "README.md");
    const readme = readSafe(readmePath);
    if (readme?.includes(START_MARKER)) targets.push({ readmePath, readme });
  }
}

const outdated: string[] = [];
for (const { readmePath, readme } of targets) {
  const dir = path.dirname(readmePath);
  const updated = applyBlock(
    readme,
    renderBlock(readPackageJson(dir), root, dir),
  );
  if (updated == null || updated === readme) continue;
  outdated.push(path.relative(ROOT, readmePath));
  if (!check) writeFileSync(readmePath, updated);
}

const list = outdated.map((file) => `- ${file}`).join("\n");
if (list) {
  if (check) {
    console.error(
      `\
Outdated:
${list}

Run \`node scripts/${basename(import.meta.url)}`,
    );
    process.exit(1);
  }

  console.log(`\
Updated:
${list}`);
}
